module.exports = Object.freeze({
    JOIN_MATCHMAKING: 'JOIN_MATCHMAKING',
    QUEUE_SIZE: 'QUEUE_SIZE',
    GAME_CREATED: 'GAME_CREATED',
    PLAYER_READY: 'PLAYER_READY',
    CARDS: 'CARDS',
    NARRATOR: 'NARRATOR',
    THEME: 'THEME',
    PLAY_CARD: 'PLAY_CARD',
    CARD_PLAYED: 'CARD_PLAYED',
    REVEAL_CARD: 'REVEAL_CARD',
    PICK_CARD: 'PICK_CARD',
    CARD_PICKED: 'CARD_PICKED',
    TRICK: 'TRICK',
    NEW_TURN: 'NEW_TURN',
    GAME_OVER: 'GAME_OVER',
    CONTEXT: 'CONTEXT',
    START_TURN: 'START_TURN'
});

